# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."comfyui-supervisor" = {
    image = "ghcr.io/ai-dock/comfyui:pytorch-2.3.0-py3.10-v2-cuda-12.1.1-base-22.04";
    environment = {
      "AUTO_UPDATE" = "false";
      "CF_QUICK_TUNNELS" = "true";
      "CF_TUNNEL_TOKEN" = "";
      "CIVITAI_TOKEN" = "";
      "COMFYUI_ARGS" = "";
      "COMFYUI_METRICS_PORT" = "28188";
      "COMFYUI_PORT_HOST" = "8188";
      "COMFYUI_URL" = "";
      "DIRECT_ADDRESS" = "127.0.0.1";
      "DIRECT_ADDRESS_GET_WAN" = "false";
      "HF_TOKEN" = "";
      "JUPYTER_METRICS_PORT" = "28888";
      "JUPYTER_PORT_HOST" = "8888";
      "JUPYTER_URL" = "";
      "SERVERLESS" = "false";
      "SERVICEPORTAL_METRICS_PORT" = "21111";
      "SERVICEPORTAL_PORT_HOST" = "1111";
      "SERVICEPORTAL_URL" = "";
      "SSH_PORT_HOST" = "2222";
      "SYNCTHING_TRANSPORT_PORT_HOST" = "22999";
      "SYNCTHING_UI_PORT_HOST" = "8384";
      "SYNCTHING_URL" = "";
      "WEB_ENABLE_AUTH" = "true";
      "WEB_ENABLE_HTTPS" = "false";
      "WEB_PASSWORD" = "password";
      "WEB_USER" = "user";
      "WORKSPACE" = "/workspace";
      "WORKSPACE_SYNC" = "false";
    };
    volumes = [
      "/home/metamageia/.dotfiles/build/COPY_ROOT_1/opt/ai-dock/api-wrapper:/opt/ai-dock/api-wrapper:rw"
      "/home/metamageia/.dotfiles/config/authorized_keys:/root/.ssh/authorized_keys_mount:rw"
      "/home/metamageia/.dotfiles/workspace:/workspace:rw,rshared"
    ];
    ports = [
      "2222:22/tcp"
      "1111:1111/tcp"
      "8188:8188/tcp"
      "8888:8888/tcp"
      "8384:8384/tcp"
      "22999:22999/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--device=nvidia.com/gpu=all"
      "--network-alias=supervisor"
      "--network=comfyui_default"
    ];
  };
  systemd.services."docker-comfyui-supervisor" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-comfyui_default.service"
    ];
    requires = [
      "docker-network-comfyui_default.service"
    ];
    partOf = [
      "docker-compose-comfyui-root.target"
    ];
    wantedBy = [
      "docker-compose-comfyui-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-comfyui_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f comfyui_default";
    };
    script = ''
      docker network inspect comfyui_default || docker network create comfyui_default
    '';
    partOf = ["docker-compose-comfyui-root.target"];
    wantedBy = ["docker-compose-comfyui-root.target"];
  };

  # Builds
  systemd.services."docker-build-comfyui-supervisor" = {
    path = [pkgs.docker pkgs.git];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/metamageia/.dotfiles/build
      docker build -t ghcr.io/ai-dock/comfyui:pytorch-2.3.0-py3.10-v2-cuda-12.1.1-base-22.04 -t ghcr.io/ai-dock/comfyui:pytorch-2.3.0-py3.10-v2-cuda-12.1.1-base-22.04:ghcr.io/ai-dock/comfyui:pytorch-2.3.0-py3.10-v2-cuda-12.1.1-base-22.04 --build-arg IMAGE_BASE=ghcr.io/ai-dock/python:3.10-v2-cuda-12.1.1-base-22.04 --build-arg PYTHON_VERSION=3.10 --build-arg PYTORCH_VERSION=2.4.1 --build-arg COMFYUI_BUILD_REF= .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-comfyui-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
