# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."vrising-vrising" = {
    image = "trueosiris/vrising";
    environment = {
      "SERVERNAME" = "vrising-TrueOsiris";
      "TZ" = "Europe/Paris";
    };
    volumes = [
      "/vrising/persistentdata:/mnt/vrising/persistentdata:rw"
      "/vrising/server:/mnt/vrising/server:rw"
    ];
    ports = [
      "9876:9876/udp"
      "9877:9877/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vrising"
      "--network=vrising_default"
    ];
  };
  systemd.services."docker-vrising-vrising" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-vrising_default.service"
    ];
    requires = [
      "docker-network-vrising_default.service"
    ];
    partOf = [
      "docker-compose-vrising-root.target"
    ];
    wantedBy = [
      "docker-compose-vrising-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-vrising_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f vrising_default";
    };
    script = ''
      docker network inspect vrising_default || docker network create vrising_default
    '';
    partOf = [ "docker-compose-vrising-root.target" ];
    wantedBy = [ "docker-compose-vrising-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vrising-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
