keys:
  - users:
    - &metamageia age1t89rkzpg93a7fu9nrle05fsqtxyvk82fnau0vp8we0pqvdptc9nq5qlnm5
creation_rules:
  - path_regex: "secrets/hermes.secrets\\.yaml$"
    key_groups:
    - age:
      - *metamageia
  - path_regex: "secrets/personal.secrets\\.yaml$"
    key_groups:
    - age:
      - *metamageia
  - path_regex: "secrets/saiadha-tunnel\\.json$"
    key_groups:
    - age:
      - *metamageia
  - path_regex: "secrets/hermes-auth\\.json$"
    key_groups:
    - age:
      - *metamageia
  - path_regex: "secrets/homelab.secrets\\.env$"
    key_groups:
    - age:
      - *metamageia
  - path_regex: "secrets/homelab.secrets\\.yaml$"
    key_groups:
    - age:
      - *metamageia
