# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."pihole" = {
    image = "pihole/pihole:latest";
    environment = {
      "FTLCONF_dns_listeningMode" = "all";
      "FTLCONF_webserver_api_password" = "correct horse battery staple";
      "TZ" = "Europe/London";
    };
    volumes = [
      "/home/metamageia/.dotfiles/etc-pihole:/etc/pihole:rw"
    ];
    ports = [
      "53:53/tcp"
      "53:53/udp"
      "80:80/tcp"
      "443:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--cap-add=SYS_NICE"
      "--cap-add=SYS_TIME"
      "--network-alias=pihole"
      "--network=pihole_default"
    ];
  };
  systemd.services."podman-pihole" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-pihole_default.service"
    ];
    requires = [
      "podman-network-pihole_default.service"
    ];
    partOf = [
      "podman-compose-pihole-root.target"
    ];
    wantedBy = [
      "podman-compose-pihole-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-pihole_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f pihole_default";
    };
    script = ''
      podman network inspect pihole_default || podman network create pihole_default
    '';
    partOf = [ "podman-compose-pihole-root.target" ];
    wantedBy = [ "podman-compose-pihole-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-pihole-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
