
{ pkgs, lib, ... }:

{


  # Containers
  virtualisation.oci-containers.containers."jellyseerr" = {
    image = "fallenbagel/jellyseerr:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "America/Chicago";
    };
    volumes = [
      "/srv/servarr/jellyseerr/config:/config:rw"
    ];
    ports = [
      "5055:5055/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jellyseerr"
      "--network=servarr_default"
    ];
  };
  systemd.services."docker-jellyseerr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container jellyseerr generated by compose2nix.";
    after = [
      "docker-network-servarr_default.service"
    ];
    requires = [
      "docker-network-servarr_default.service"
    ];
    partOf = [
      "docker-compose-servarr-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "lscr.io/linuxserver/prowlarr:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "America/Chicago";
    };
    volumes = [
      "/srv/servarr/prowlarr/config:/config:rw"
    ];
    ports = [
      "9696:9696/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=prowlarr"
      "--network=servarr_default"
    ];
  };
  systemd.services."docker-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container prowlarr generated by compose2nix.";
    after = [
      "docker-network-servarr_default.service"
    ];
    requires = [
      "docker-network-servarr_default.service"
    ];
    partOf = [
      "docker-compose-servarr-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "America/Chicago";
    };
    volumes = [
      "/srv/downloads:/downloads:rw"
      "/srv/servarr/qbittorrent/config:/config:rw"
    ];
    ports = [
      "8080:8080/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=qbittorrent"
      "--network=servarr_default"
    ];
  };
  systemd.services."docker-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container qbittorrent generated by compose2nix.";
    after = [
      "docker-network-servarr_default.service"
    ];
    requires = [
      "docker-network-servarr_default.service"
    ];
    partOf = [
      "docker-compose-servarr-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."radarr" = {
    image = "lscr.io/linuxserver/radarr:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "America/Chicago";
    };
    volumes = [
      "/srv/downloads:/downloads:rw"
      "/srv/media/Movies:/movies:rw"
      "/srv/servarr/radarr/config:/config:rw"
    ];
    ports = [
      "7878:7878/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=radarr"
      "--network=servarr_default"
    ];
  };
  systemd.services."docker-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container radarr generated by compose2nix.";
    after = [
      "docker-network-servarr_default.service"
    ];
    requires = [
      "docker-network-servarr_default.service"
    ];
    partOf = [
      "docker-compose-servarr-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sonarr" = {
    image = "lscr.io/linuxserver/sonarr:latest";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "America/Chicago";
    };
    volumes = [
      "/srv/downloads:/downloads:rw"
      "/srv/media/TV:/tv:rw"
      "/srv/servarr/sonarr/config:/config:rw"
    ];
    ports = [
      "8989:8989/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sonarr"
      "--network=servarr_default"
    ];
  };
  systemd.services."docker-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container sonarr generated by compose2nix.";
    after = [
      "docker-network-servarr_default.service"
    ];
    requires = [
      "docker-network-servarr_default.service"
    ];
    partOf = [
      "docker-compose-servarr-root.target"
    ];
    wantedBy = [
      "docker-compose-servarr-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-servarr_default" = {
    unitConfig.Description = "Network servarr_default generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f servarr_default";
    };
    script = ''
      docker network inspect servarr_default || docker network create servarr_default
    '';
    partOf = [ "docker-compose-servarr-root.target" ];
    wantedBy = [ "docker-compose-servarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-servarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
